services:
- docker

script:
# build new image
- docker build --rm=true -t yogdaan/blockchain-diploma:latest

jobs:
  include:
  # push image to dockerhub
  - stage: build-push
    if: branch = master AND type != pull_request
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --rm=true -t yogdaan/blockchain-diploma:latest .
    - docker push yogdaan/blockchain-diploma:latest
